backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "_site/assets/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
collections:
 - name: "blog"
   label: "Blog"
   folder: "src/blog"
   create: true
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   fields: 
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Description", name: "description", widget: "markdown" }
    - { label: "Author", name: "author", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Category", name: "category", widget: "select", options: ["News", "Tutorial", "Editorial"] }
    - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
    - { label: "Featured Image", name: "image", widget: "image" }
    - { label: "Image Caption", name: "imageAlt", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }


